### ISSUE TITLE
Update to API will cause issue with Group User Call Statistics

### ISSUE THREAD

**Issue by Jordan-Prescott** [Jordan-Prescott/odins_spear#72]
[Odin Patch Release 7.4.17 is now available](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpost.spmailtechno.com%2Ff%2Fa%2FSRrRNk39dKKxX2tlJha7Tg~~%2FAAFK8wA~%2FRgRoem6IP0TYaHR0cDovL3Jldi1pby1vZGluLnJlbGVhc2Vub3Rlcy5pby9yZWxlYXNlL0QybmRmLW9kaW4tcGF0Y2gtcmVsZWFzZS03NDE3LWlzLW5vdy1hdmFpbGFibGU_dXRtX3NvdXJjZT1hbm5vdW5jZW1lbnQmdXRtX2NhbXBhaWduPUQybmRmJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NvbnRlbnQ9T2RpbiUyQlBhdGNoJTJCUmVsZWFzZSUyQjcuNC4xNyUyQmlzJTJCbm93JTJCYXZhaWxhYmxlVwNzcGNCCmaViemXZsDocThSHkpvcmRhbi5wcmVzY290dEBmb3VydGVlbmlwLmNvbVgEAAAAAA~~&data=05%7C02%7CJordan.prescott%40fourteenip.com%7Cdc84d592b2b144da68a208dca678f21f%7Ced1d949ddd214d1fa3b06c273d5b1ae8%7C0%7C0%7C638568285590707638%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=4KfgiAn9VzGmlNQwRbp%2FtGYN6VHj%2B4ZMf5TbWmF7Gdg%3D&reserved=0)
Greetings Odin users! This batch of release notes covers all the features, updates, and bug fixes published throughout July, 2024. 

Normally, we segment releases into smaller chunks, but in this case the Odin team feels grouping the last few releases together makes the most sense, as many front and backend elements distrubuted across these releases work in concert. 

Accordingly, we strongly advise any client wishing to upgrade beyond 7.4.13 to request an upgrade directly to 7.4.17. 

As a reminder, all of these features are live and available for review in your instance of Odin via the Lab feature. 

Please email care@rev.io if you'd like to get on the schedule for an upgrade.

New Features
ODIN WEB

For User Bulk Features, the Voice Messaging User Screen CSV report download now includes 3 additional columns: sendVoiceMessageNotifyEmail, voiceMessageDeliveryEmailAddress, and voiceMessageCarbonCopyEmailAddress. [ADO-10600]
Enterprise and group admins can now enable and disable admins at their level of clearance or lower. [9863]
Updates
ODIN WEB

Improved the performance of the Service Utilization Report [ADO-8413] 
Added the ability to filter the Group User Call Report to remove users who do not have any calls during the designated period [ADO-10633] 
Odin group Devices and group Device Configuration as well as user Devices were in some cases requiring tag values. Odin now allows null Tag Values in all cases as well as correctly passes along "true" or "false" values. [ADO-10785] 
While on the user landing page, the links to settings for calling features are now in focus order. [ADO-9665]
The downloadable CSV report User Bulk Features - Voice Messaging User Screen now includes an additional column: voiceMessageNotifyEmailAddress. [ADO-11272] 
When using the "Enable Authentication" option of the user create callback, the system should update the user authentication and raise a "user.authentication.update" event regardless of whether or not the authentication service is previously enabled. [ADO-11585] 
ODIN API

Performing a GET call on the call records user stats returns an empty array instead of an object with null properties when no matching records are found. [ADO-10847] 
Bugfixes
ODIN WEB

Corrected a bug that was preventing hunt group agent reordering. [ADO-11439] 
Fixed various bugs and implemented several optimizations for date picker. [ADO-10644]
ODIN API

Corrected issues with the Phonism Webhook fix for the user.busyLampField.update event. [ADO-10727]

**Comment by LivCurtis** [comment]
Odin has changed what is returned from the api null/0 which is going to break the method (group user call statitstics) we built in reporter.py. Need to adjust for this
