### ISSUE TITLE
User association error

### ISSUE THREAD

**Issue by AhmedAtxha** [Jordan-Prescott/odins_spear#95]
When running the user association script I ran into this error. 

![image](https://github.com/user-attachments/assets/8a919ba3-eea7-4ffd-824c-591eede0e069)

To fix add a exception
![image](https://github.com/user-attachments/assets/157ffffe-7b37-4ee5-b5d8-c2509533a019)

and also a print 
![image](https://github.com/user-attachments/assets/865f1db6-2a11-4934-978e-ea624a0164da)
.

I also noticed that the pickup group returns nothing when the user is in a pickup group.

Code:
![image](https://github.com/user-attachments/assets/a68c69dc-ecf5-4002-8b5f-24dbf6e51dde)

Pickup Group
![image](https://github.com/user-attachments/assets/d5e8a9f1-b7c2-4e0f-b61a-11010dc3a735)

**Comment by Chopped4Life** [comment]
Added an exception however if the user is in a Pickup Group it still does not pull anything.

Currently looking into this issue, may have to raise with rev.io
